// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.es.domain;

import com.github.lbroudoux.es.domain.Tweet;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Persistent;
import org.springframework.data.elasticsearch.annotations.Document;

privileged aspect Tweet_Roo_Elasticsearch_Entity {
    
    declare @type: Tweet: @Persistent;
    
    declare @type: Tweet: @Document(indexName = "tweets", type = "tweet");
    
    @Id
    private String Tweet.id;
    
    public String Tweet.getId() {
        return this.id;
    }
    
    public void Tweet.setId(String id) {
        this.id = id;
    }
    
}
