// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.es.repository;

import com.github.lbroudoux.es.domain.Tweet;
import com.github.lbroudoux.es.repository.TweetRepository;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;

privileged aspect TweetRepository_Roo_Elasticsearch_Repository {
    
    declare parents: TweetRepository extends PagingAndSortingRepository<Tweet, String>;
    
    declare @type: TweetRepository: @Repository;
    
}
