// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.es.web;

import com.github.lbroudoux.es.domain.Tweet;
import com.github.lbroudoux.es.service.TweetService;
import com.github.lbroudoux.es.web.TweetController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect TweetController_Roo_Controller {
    
    @Autowired
    TweetService TweetController.tweetService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String TweetController.create(@Valid Tweet tweet, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, tweet);
            return "tweets/create";
        }
        uiModel.asMap().clear();
        tweetService.saveTweet(tweet);
        return "redirect:/tweets/" + encodeUrlPathSegment(tweet.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String TweetController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Tweet());
        return "tweets/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String TweetController.show(@PathVariable("id") String id, Model uiModel) {
        uiModel.addAttribute("tweet", tweetService.findTweet(id));
        uiModel.addAttribute("itemId", id);
        return "tweets/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String TweetController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("tweets", tweetService.findTweetEntries(firstResult, sizeNo));
            float nrOfPages = (float) tweetService.countAllTweets() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("tweets", tweetService.findAllTweets());
        }
        return "tweets/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String TweetController.update(@Valid Tweet tweet, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, tweet);
            return "tweets/update";
        }
        uiModel.asMap().clear();
        tweetService.updateTweet(tweet);
        return "redirect:/tweets/" + encodeUrlPathSegment(tweet.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String TweetController.updateForm(@PathVariable("id") String id, Model uiModel) {
        populateEditForm(uiModel, tweetService.findTweet(id));
        return "tweets/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String TweetController.delete(@PathVariable("id") String id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Tweet tweet = tweetService.findTweet(id);
        tweetService.deleteTweet(tweet);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/tweets";
    }
    
    void TweetController.populateEditForm(Model uiModel, Tweet tweet) {
        uiModel.addAttribute("tweet", tweet);
    }
    
    String TweetController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
