// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.es.service;

import com.github.lbroudoux.es.domain.Tweet;
import com.github.lbroudoux.es.service.TweetService;
import java.util.List;

privileged aspect TweetService_Roo_Service {
    
    public abstract long TweetService.countAllTweets();    
    public abstract void TweetService.deleteTweet(Tweet tweet);    
    public abstract Tweet TweetService.findTweet(String id);    
    public abstract List<Tweet> TweetService.findAllTweets();    
    public abstract List<Tweet> TweetService.findTweetEntries(int firstResult, int maxResults);    
    public abstract void TweetService.saveTweet(Tweet tweet);    
    public abstract Tweet TweetService.updateTweet(Tweet tweet);    
}
