// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.es.service;

import com.github.lbroudoux.es.domain.Tweet;
import com.github.lbroudoux.es.repository.TweetRepository;
import com.github.lbroudoux.es.service.TweetServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TweetServiceImpl_Roo_Service {
    
    declare @type: TweetServiceImpl: @Service;
    
    declare @type: TweetServiceImpl: @Transactional;
    
    @Autowired
    TweetRepository TweetServiceImpl.tweetRepository;
    
    public long TweetServiceImpl.countAllTweets() {
        return tweetRepository.count();
    }
    
    public void TweetServiceImpl.deleteTweet(Tweet tweet) {
        tweetRepository.delete(tweet);
    }
    
    public Tweet TweetServiceImpl.findTweet(String id) {
        return tweetRepository.findOne(id);
    }
    
    public List<Tweet> TweetServiceImpl.findAllTweets() {
        return tweetRepository.findAll(new org.springframework.data.domain.PageRequest(0, Math.max(1, (int)tweetRepository.count()))).getContent();
    }
    
    public List<Tweet> TweetServiceImpl.findTweetEntries(int firstResult, int maxResults) {
        return tweetRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void TweetServiceImpl.saveTweet(Tweet tweet) {
        tweetRepository.save(tweet);
    }
    
    public Tweet TweetServiceImpl.updateTweet(Tweet tweet) {
        return tweetRepository.save(tweet);
    }
    
}
